### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by mogulano**
Please provide an email where to send reports about vulnerabilities in this project

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [ ] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 包体积优化 / Package size optimization
- [ ] 性能优化 / Performance optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### CODE REVIEW

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/28679

**Comment by mogulano** [comment]
The author didn't respond to our emails. Could you please write an email to securitylab@github.com with the subject umijs/dumi so we could deliver you security report instead of creating a public issue?

**Comment by PeachScript** [comment]
> The author didn't respond to our emails. Could you please write an email to [securitylab@github.com](mailto:securitylab@github.com) with the subject umijs/dumi so we could deliver you security report instead of creating a public issue?

Sent, thank you

**Comment by mogulano** [comment]
Replied. Please write here if not delivered.

**Pull request closed without merging**
