### PR TITLE
fix:  property 'path' of undefined（#872）

### PR DESCRIPTION
**Pull request by wayofwade**
fix:  property 'path' of undefined（#872）

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] bug 修复 / Fix bug

### 🔗 相关 Issue / Related Issue
https://github.com/umijs/dumi/issues/872

当我使用1.1.26版本的dumi的时候，yarn dev的时候产生了报错信息，不能正常启动，报错信息如下：
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at /Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/redirect.js:133:196
    at Array.forEach (<anonymous>)
    at Object.redirect (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/redirect.js:87:10)
    at /Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:63:27
    at Array.reduce (<anonymous>)
    at RouteDecorator.process (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:62:28)
    at _default (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:82:20)
    at /Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/getRouteConfig.js:127:38
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/getRouteConfig.js:70:103)
✨  Done in 18.18s.

我的.umirc.js的配置如下
	menus: {
		'/docs': [
			{
				title: '通用',
				children: ['../docs/docs/common/start.md', '../docs/docs/common/changelog.md'],
			}
                 ]
         }

### 💡 需求背景和解决方案 / Background or solution
在@umijs/preset-dumi/lib/routes/decorator/redirect.js:133:196 的path前面加上判空处理，则正常启动项目

解决了项目可以不呢正常启动的问题

### 📝 更新日志 / Changelog

暂无风险，只添加了判空处理

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fix property 'path' of undefined   |
| 🇨🇳 Chinese |    对path进行了判空处理       |

### CODE REVIEW

**Comment by PeachScript** [comment]
先找到报错的原因再讨论修复方案，请在 issue 里提供最小可复现仓库

**Comment by wayofwade** [comment]
> 先找到报错的原因再讨论修复方案，请在 issue 里提供最小可复现仓库

你好 这个是我的demo地址：https://github.com/wayofwade/dumi-fix-bug-demo

复现步骤：1-yarn install 
                   2-yarn start

**Comment by wayofwade** [comment]
> > 先找到报错的原因再讨论修复方案，请在 issue 里提供最小可复现仓库
> 
> 你好 这个是我的demo地址：https://github.com/wayofwade/dumi-fix-bug-demo
> 
> 复现步骤：1-yarn install
> 2-yarn start
>3- 报错了
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at /Users/chencongcong/code/web/dumi-fix-bug-demo/node_modules/@umijs/preset-dumi/lib/routes/decorator/redirect.js:133:196

**Comment by PeachScript** [comment]
PR 关闭，原因参考 #872

**Pull request closed without merging**
